#!/usr/bin/env python3
"""
Farm RPG Item Image & Name Downloader
-------------------------------------
Fetches the complete item database from buddy.farm and downloads authentic
item icons directly from farmrpg.com into the `assets/` directory.

Features:
- Pure Python 3 standard library (no pip dependencies required).
- Polite concurrency with automatic retry and exponential backoff.
- Resumable: automatically skips already downloaded images.
- Filenames formatted as `<Item Name>.png` (matching game conventions).
- Generates `data/items.json` and `js/items-data.js` for the helper web app.
"""

import os
import sys
import re
import json
import time
import random
import argparse
import urllib.request
import urllib.error
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

SEARCH_JSON_URL = "https://buddy.farm/search.json"
BASE_ASSET_URL = "https://farmrpg.com"
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT_DIR = SCRIPT_DIR.parent
ASSETS_DIR = ROOT_DIR / "assets"
DATA_DIR = ROOT_DIR / "data"
JS_DIR = ROOT_DIR / "js"

# Extra items/currencies that may not be listed under /i/ in search.json
ADDITIONAL_ITEMS = [
    {"name": "Silver", "image": "/img/items/silver.png", "href": "/i/silver/"},
    {"name": "Gold", "image": "/img/items/gold.png", "href": "/i/gold/"},
]

SAFE_FILENAME_RE = re.compile(r'[\\/:*?"<>|]')


def sanitize_filename(name: str) -> str:
    """Sanitizes an item name to be safely used as a filename."""
    return SAFE_FILENAME_RE.sub("_", name.strip())


def fetch_json(url: str):
    """Fetches JSON data from a URL using standard urllib."""
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8"))


def load_catalog():
    """Fetches the full catalog from buddy.farm and enriches with extras."""
    print(f"Fetching item catalog from {SEARCH_JSON_URL}...")
    raw = fetch_json(SEARCH_JSON_URL)

    items_map = {}
    for entry in raw:
        href = entry.get("href") or ""
        name = (entry.get("name") or "").strip()
        img = entry.get("image") or ""
        if href.startswith("/i/") and name and img:
            items_map[name] = {
                "name": name,
                "image": img,
                "href": href,
                "filename": f"{sanitize_filename(name)}.png",
            }

    for extra in ADDITIONAL_ITEMS:
        name = extra["name"]
        if name not in items_map:
            items_map[name] = {
                "name": name,
                "image": extra["image"],
                "href": extra["href"],
                "filename": f"{sanitize_filename(name)}.png",
            }

    items = sorted(list(items_map.values()), key=lambda x: x["name"].lower())
    print(f"Catalog loaded: {len(items)} unique Farm RPG items found.")
    return items


def save_catalog_files(items):
    """Saves items data to JSON and JS files for use in the app."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    JS_DIR.mkdir(parents=True, exist_ok=True)

    json_path = DATA_DIR / "items.json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(items, f, indent=2, ensure_ascii=False)
    print(f"Saved JSON catalog to: {json_path}")

    js_path = JS_DIR / "items-data.js"
    items_array_str = json.dumps(items, indent=2, ensure_ascii=False)

    js_content = f"""// AUTO-GENERATED by scripts/download_farmrpg_items.py
// Total items: {len(items)}
// Source: buddy.farm / farmrpg.com

export const ALL_FARM_RPG_ITEMS = {items_array_str};

export const ITEM_NAME_MAP = new Map(
  ALL_FARM_RPG_ITEMS.map(item => [item.name.toLowerCase(), item])
);

export const KNOWN_ITEM_NAMES = ALL_FARM_RPG_ITEMS.map(item => item.name);

/**
 * Returns the relative image path in assets/ for a given item name.
 */
export function getItemImageFilename(itemName) {{
  if (!itemName) return null;
  const match = ITEM_NAME_MAP.get(itemName.trim().toLowerCase());
  return match ? match.filename : `${{itemName.trim()}}.png`;
}}

/**
 * Checks if an item exists in the authentic Farm RPG catalog.
 */
export function isKnownFarmRPGItem(itemName) {{
  if (!itemName) return false;
  return ITEM_NAME_MAP.has(itemName.trim().toLowerCase());
}}
"""
    with open(js_path, "w", encoding="utf-8") as f:
        f.write(js_content)
    print(f"Saved JavaScript module to: {js_path}")


def download_single_image(item, target_dir: Path, overwrite: bool = False, max_retries: int = 4):
    """Downloads one item image with exponential backoff on network errors."""
    filename = item["filename"]
    dest_path = target_dir / filename

    if not overwrite and dest_path.exists() and dest_path.stat().st_size > 0:
        return item["name"], "SKIPPED", dest_path.stat().st_size

    image_rel_path = item["image"]
    clean_path = image_rel_path.split("?")[0]
    img_url = f"{BASE_ASSET_URL}{clean_path}"

    headers = {
        "User-Agent": USER_AGENT,
        "Referer": "https://farmrpg.com/",
        "Accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
        "Connection": "keep-alive",
    }

    for attempt in range(1, max_retries + 1):
        try:
            req = urllib.request.Request(img_url, headers=headers)
            with urllib.request.urlopen(req, timeout=25) as resp:
                data = resp.read()
                if len(data) == 0:
                    return item["name"], "EMPTY", 0
                with open(dest_path, "wb") as f:
                    f.write(data)
                # Polite pacing to avoid triggering rate limiter
                time.sleep(0.04)
                return item["name"], "DOWNLOADED", len(data)

        except urllib.error.HTTPError as e:
            if e.code in (429, 503, 502, 504):
                sleep_time = (2 ** attempt) + random.uniform(0.5, 1.5)
                time.sleep(sleep_time)
                continue
            return item["name"], f"HTTP_{e.code}", 0

        except Exception as e:
            if attempt < max_retries:
                sleep_time = (1.5 ** attempt) + random.uniform(0.3, 1.0)
                time.sleep(sleep_time)
                continue
            return item["name"], f"ERROR: {str(e)[:35]}", 0

    return item["name"], "MAX_RETRIES_EXCEEDED", 0


def main():
    parser = argparse.ArgumentParser(description="Download Farm RPG item names and images.")
    parser.add_argument("--limit", type=int, default=0, help="Download only the first N items")
    parser.add_argument("--search", type=str, default="", help="Filter items containing a search query")
    parser.add_argument("--overwrite", action="store_true", help="Re-download and overwrite existing files")
    parser.add_argument("--concurrency", type=int, default=5, help="Number of concurrent worker threads (default: 5)")
    parser.add_argument("--data-only", action="store_true", help="Only generate items.json and items-data.js")
    args = parser.parse_args()

    ASSETS_DIR.mkdir(parents=True, exist_ok=True)

    items = load_catalog()
    save_catalog_files(items)

    if args.data_only:
        print("Data catalog files created. Image download skipped (--data-only).")
        return

    queue = items
    if args.search:
        q = args.search.lower()
        queue = [it for it in queue if q in it["name"].lower()]
        print(f"Filtered by search '{args.search}': {len(queue)} items matched.")

    if args.limit > 0:
        queue = queue[:args.limit]
        print(f"Limited to first {len(queue)} items.")

    total = len(queue)
    print(f"Starting download of {total} images using {args.concurrency} concurrent workers...")

    stats = {"DOWNLOADED": 0, "SKIPPED": 0, "FAILED": 0}
    start_time = time.time()

    with ThreadPoolExecutor(max_workers=args.concurrency) as executor:
        futures = {
            executor.submit(download_single_image, item, ASSETS_DIR, args.overwrite): item
            for item in queue
        }

        completed = 0
        for future in as_completed(futures):
            completed += 1
            name, status, size = future.result()
            if status == "DOWNLOADED":
                stats["DOWNLOADED"] += 1
            elif status == "SKIPPED":
                stats["SKIPPED"] += 1
            else:
                stats["FAILED"] += 1
                print(f"[{completed}/{total}] {name}: {status}")

            if completed % 100 == 0 or completed == total:
                elapsed = time.time() - start_time
                print(f"Progress: {completed}/{total} ({completed/total*100:.1f}%) | "
                      f"Downloaded: {stats['DOWNLOADED']} | Skipped: {stats['SKIPPED']} | "
                      f"Failed: {stats['FAILED']} | Time: {elapsed:.1f}s")

    print("\n-------------------------------------------")
    print(f"All operations finished in {time.time() - start_time:.2f}s!")
    print(f"Total processed: {total}")
    print(f"Newly downloaded: {stats['DOWNLOADED']}")
    print(f"Already existed (skipped): {stats['SKIPPED']}")
    print(f"Errors/Failed: {stats['FAILED']}")
    print(f"Images are saved in: {ASSETS_DIR}")
    print("-------------------------------------------")


if __name__ == "__main__":
    main()
