#!/usr/bin/env node
/**
 * Farm RPG Item Image & Name Downloader (Node.js)
 * -----------------------------------------------
 * Fetches the complete item database from buddy.farm and downloads authentic
 * item icons directly from farmrpg.com into the `assets/` directory.
 *
 * Uses built-in fetch and fs/promises (Node 18+).
 */

import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT_DIR = path.resolve(__dirname, '..');
const ASSETS_DIR = path.join(ROOT_DIR, 'assets');
const DATA_DIR = path.join(ROOT_DIR, 'data');
const JS_DIR = path.join(ROOT_DIR, 'js');

const SEARCH_JSON_URL = 'https://buddy.farm/search.json';
const BASE_ASSET_URL = 'https://farmrpg.com';
const USER_AGENT = 'FarmRPG-Helper-Bot/1.0 (+https://github.com/m-sarabi/farm-rpg-helper)';

const ADDITIONAL_ITEMS = [
  { name: 'Silver', image: '/img/items/silver.png', href: '/i/silver/' },
  { name: 'Gold', image: '/img/items/gold.png', href: '/i/gold/' },
];

function sanitizeFilename(name) {
  return name.trim().replace(/[\\/:*?"<>|]/g, '_');
}

async function loadCatalog() {
  console.log(`Fetching item catalog from ${SEARCH_JSON_URL}...`);
  const resp = await fetch(SEARCH_JSON_URL, { headers: { 'User-Agent': USER_AGENT } });
  if (!resp.ok) throw new Error(`Failed to fetch catalog: ${resp.status}`);
  const raw = await resp.json();

  const itemsMap = new Map();
  for (const entry of raw) {
    const href = entry.href || '';
    const name = (entry.name || '').trim();
    const img = entry.image || '';
    if (href.startsWith('/i/') && name && img) {
      itemsMap.set(name, {
        name,
        image: img,
        href,
        filename: `${sanitizeFilename(name)}.png`,
      });
    }
  }

  for (const extra of ADDITIONAL_ITEMS) {
    if (!itemsMap.has(extra.name)) {
      itemsMap.set(extra.name, {
        name: extra.name,
        image: extra.image,
        href: extra.href,
        filename: `${sanitizeFilename(extra.name)}.png`,
      });
    }
  }

  const items = Array.from(itemsMap.values()).sort((a, b) =>
    a.name.localeCompare(b.name, undefined, { sensitivity: 'base' })
  );
  console.log(`Catalog loaded: ${items.length} unique Farm RPG items found.`);
  return items;
}

async function saveCatalogFiles(items) {
  await fsp.mkdir(DATA_DIR, { recursive: true });
  await fsp.mkdir(JS_DIR, { recursive: true });

  const jsonPath = path.join(DATA_DIR, 'items.json');
  await fsp.writeFile(jsonPath, JSON.stringify(items, null, 2), 'utf-8');
  console.log(`Saved JSON catalog to: ${jsonPath}`);

  const jsPath = path.join(JS_DIR, 'items-data.js');
  const itemsJson = JSON.stringify(items, null, 2);
  const jsContent = `// AUTO-GENERATED by scripts/download_farmrpg_items.js
// Total items: ${items.length}
// Source: buddy.farm / farmrpg.com

export const ALL_FARM_RPG_ITEMS = ${itemsJson};

export const ITEM_NAME_MAP = new Map(
  ALL_FARM_RPG_ITEMS.map(item => [item.name.toLowerCase(), item])
);

export const KNOWN_ITEM_NAMES = ALL_FARM_RPG_ITEMS.map(item => item.name);

export function getItemImageFilename(itemName) {
  if (!itemName) return null;
  const match = ITEM_NAME_MAP.get(itemName.trim().toLowerCase());
  return match ? match.filename : \`\${itemName.trim()}.png\`;
}

export function isKnownFarmRPGItem(itemName) {
  if (!itemName) return false;
  return ITEM_NAME_MAP.has(itemName.trim().toLowerCase());
}
`;
  await fsp.writeFile(jsPath, jsContent, 'utf-8');
  console.log(`Saved JavaScript module to: ${jsPath}`);
}

async function downloadSingleImage(item, overwrite = false) {
  const destPath = path.join(ASSETS_DIR, item.filename);
  if (!overwrite && fs.existsSync(destPath)) {
    const stat = await fsp.stat(destPath);
    if (stat.size > 0) {
      return { name: item.name, status: 'SKIPPED', size: stat.size };
    }
  }

  const cleanPath = item.image.split('?')[0];
  const imgUrl = `${BASE_ASSET_URL}${cleanPath}`;

  try {
    const res = await fetch(imgUrl, {
      headers: {
        'User-Agent': USER_AGENT,
        Referer: 'https://farmrpg.com/',
      },
    });
    if (!res.ok) {
      return { name: item.name, status: `HTTP_${res.status}`, size: 0 };
    }
    const buffer = Buffer.from(await res.arrayBuffer());
    if (buffer.length === 0) {
      return { name: item.name, status: 'EMPTY', size: 0 };
    }
    await fsp.writeFile(destPath, buffer);
    return { name: item.name, status: 'DOWNLOADED', size: buffer.length };
  } catch (err) {
    return { name: item.name, status: `ERROR: ${err.message}`, size: 0 };
  }
}

async function main() {
  await fsp.mkdir(ASSETS_DIR, { recursive: true });

  const items = await loadCatalog();
  await saveCatalogFiles(items);

  const concurrency = 10;
  console.log(`Starting download of ${items.length} images (concurrency: ${concurrency})...`);

  let completed = 0;
  let downloaded = 0;
  let skipped = 0;
  let failed = 0;
  const startTime = Date.now();

  async function worker(queue) {
    while (queue.length > 0) {
      const item = queue.shift();
      const res = await downloadSingleImage(item);
      completed++;
      if (res.status === 'DOWNLOADED') downloaded++;
      else if (res.status === 'SKIPPED') skipped++;
      else {
        failed++;
        console.warn(`[${completed}/${items.length}] ${res.name}: ${res.status}`);
      }

      if (completed % 100 === 0 || completed === items.length) {
        const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
        console.log(
          `Progress: ${completed}/${items.length} (${((completed / items.length) * 100).toFixed(1)}%) | ` +
          `Downloaded: ${downloaded} | Skipped: ${skipped} | Failed: ${failed} | Time: ${elapsed}s`
        );
      }
    }
  }

  const queue = [...items];
  const workers = Array.from({ length: concurrency }, () => worker(queue));
  await Promise.all(workers);

  const totalTime = ((Date.now() - startTime) / 1000).toFixed(2);
  console.log('\n-------------------------------------------');
  console.log(`All operations finished in ${totalTime}s!`);
  console.log(`Total processed: ${items.length}`);
  console.log(`Newly downloaded: ${downloaded}`);
  console.log(`Already existed (skipped): ${skipped}`);
  console.log(`Errors/Failed: ${failed}`);
  console.log(`Images saved in: ${ASSETS_DIR}`);
  console.log('-------------------------------------------');
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
